# paths to ignore during linting. Takes precedence over `included`
excluded:
  - Carthage
  - Pods
  - R.generated.swift

# Disabled rules
disabled_rules:

# Enabled non-default rules
opt_in_rules:
 - closure_spacing
 - closure_end_indentation
 - contains_over_first_not_nil
 - empty_count
# - explicit_enum_raw_value
 - explicit_init
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - let_var_whitespace
 - literal_expression_end_indentation
 - multiline_parameters
 - nimble_operator
 - number_separator
 - operator_usage_whitespace
 - overridden_super_call
 - private_action
 - private_outlet
 - prohibited_super_call
 - redundant_nil_coalescing
 - sorted_first_last
# - sorted_imports
 - vertical_parameter_alignment_on_call

# Rules customization
line_length: 160
