# paths to ignore during linting. Takes precedence over `included`
excluded:
  - Carthage
  - Pods
  - R.generated.swift

# Disabled rules
disabled_rules:

# Enabled non-default rules
opt_in_rules:
 - closure_spacing
 - closure_end_indentation
 - contains_over_first_not_nil
 - empty_count
 - explicit_init
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - let_var_whitespace
 - literal_expression_end_indentation
 - multiline_parameters
 - nimble_operator
 - number_separator
 - operator_usage_whitespace
 - overridden_super_call
 - private_action
 - private_outlet
 - prohibited_super_call
 - redundant_nil_coalescing
 - sorted_first_last
 - vertical_parameter_alignment_on_call
 - convenience_type
 - empty_string
 - fallthrough
 - fatal_error_message
 - file_name
 - force_unwrapping
 - function_default_parameter_at_end
 - lower_acl_than_parent
 - missing_docs
 - modifier_order
 - multiline_arguments
 - multiline_function_chains
 - pattern_matching_keywords
 - quick_discouraged_call
 - redundant_type_annotation
 - required_enum_case
 - single_test_class
 - strict_fileprivate
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
 - yoda_condition

# Rules customization
line_length: 140
